ENV["XCODE_VERSION"] = "~> 12.0"

lane :provisioning do |options|
  CONFIGURATION = options[:configuration] || UI.select("Select configuration:", ["Debug", "Release"])
  USERNAME = options[:username] || UI.input("Apple ID username:")

  APP_IDENTIFIER = get_build_settings(key: "PRODUCT_BUNDLE_IDENTIFIER", build_configuration: CONFIGURATION)
  TYPE = CONFIGURATION == "Debug" ? "development" : "enterprise"

  match(
    git_url: "git@github.com:AckeeScreenshoter/match-certificates.git",
    storage_mode: "git",
    team_id: "PXDF48X6VX",
    app_identifier: APP_IDENTIFIER,
    type: TYPE,
    username: USERNAME
  )
end

lane :beta do |options|
  ARCHIVE_PATH = "./outputs/Archive.xcarchive"

  sh "rm -rf ../#{ARCHIVE_PATH}"

  gym(
    scheme: "ass-app",
    clean: true,
    output_directory: ARCHIVE_PATH,
    export_options: {
      method: "enterprise"
    }
  )

  UI.important "beta lane does not upload the build itself, you have to do it manually if you need it"
end
