require 'ACKFastlane'

import(ACKFastlane.fastfilePath)

CONFIGURATIONS = {
    "Debug" => "development",
    "Release" => "enterprise",
}


INHOUSE_APPLE_ID = "unicorn@ackee.cz"
PRODUCTION_TEAM_ID = "PXDF48X6VX" # string identifier
PRODUCTION_TEAM_ID2 = "1588142" # number identifier, anyone idea for better name?

ENV["XCODE_VERSION"] = "~> 11.3"
